apiVersion: apps/v1
kind: Deployment
metadata:
  name: yotta
  labels:
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: yotta
        image: ahsan75/yotta:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80