apiVersion: v1
kind: Service
metadata:
  name: yotta-service
  labels:
    env: prod
spec:
  type: LoadBalancer
  externalIPs:
    - 143.198.40.35
  selector:
    env: prod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80